postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: nest_playground

mongodb:
  uri: mongodb://localhost:27017/nest_playground
  host: localhost
  port: 27017
  database: nest_playground
